project_id = "sfluqepcpjmupeokhwlr"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "http://127.0.0.1:54321"
additional_redirect_urls = ["https://sfluqepcpjmupeokhwlr.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_change_confirmations = true
enable_phone_confirmations = true
enable_phone_change_confirmations = true

[db]
port = 54323
shadow_port = 54324
major_version = 15

[edge_functions]
enabled = true
port = 54325

[functions.chat]
verify_jwt = false

[studio]
enabled = true
port = 54323